### ISSUE TITLE
decouple read deduplication from taxonomic filtration

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-classify#8]
Burying mvicuna (or any other tool's) unaligned read deduplication in the middle of human depletion steps (after bwa/bmtagger and before blast) was purely for historical optimization reasons and doesn't actually make much sense from a user perspective.

I propose to break read deduplication out of taxon_filter.deplete and invoke it as a separate python command (and most likely, break it as a separate WDL task too in viral-pipelines). It's notable that, as it currently exists, it's already in read_utils in viral-core, not viral-classify.

**Comment by tomkinsc** [comment]
Probably also a good time to consider porting over clumpify-based dedup https://github.com/broadinstitute/viral-ngs/pull/970
